* elisp-eldoc-flags


Additional Eldoc and completion functions for ~emacs-lisp-mode~.

** Installation

Emacs >= 26.1 is required.

*** Manual

Download the source code and put it wherever you like, e.g. into =~/.emacs.d/elisp-eldoc-flags/=

#+begin_src shell :eval no
git clone https://github.com/KarimAziev/elisp-eldoc-flags.git ~/.emacs.d/elisp-eldoc-flags/
#+end_src

Add the downloaded directory to the load path:

#+begin_src elisp :eval no
(add-to-list 'load-path "~/.emacs.d/elisp-eldoc-flags/")
(require 'elisp-eldoc-flags)
(add-hook 'emacs-lisp-mode-hook #'elisp-eldoc-flags-add-eldoc-functions)
#+end_src

#+begin_src elisp :eval no
(use-package elisp-eldoc-flags
  :straight (elisp-eldoc-flags
             :repo "KarimAziev/elisp-eldoc-flags"
             :type git
             :host github)
  :hook ((emacs-lisp-mode . elisp-eldoc-flags-add-eldoc-functions)
         (emacs-lisp-mode . elisp-eldoc-flags-add-completion-functions)))
#+end_src

** Elcoc Commands

*** elisp-eldoc-flags-add-eldoc-functions

Add extra functions to =eldoc-documentation-functions=. This functions are listed in the custom variable =elisp-eldoc-flags-functions= with default value:

- ~elisp-eldoc-flags-describe-interactive-flag~ Describe arg-descriptor inside =interactive= calls.
- ~elisp-eldoc-flags-describe-format-flag~ Describe %-sequences inside string.

*** elisp-eldoc-flags-remove-eldoc-functions

Remove =elisp-eldoc-flags-functions= from =eldoc-documentation-functions=.

** Completions commands
*** elisp-eldoc-flags-add-completion-functions

Add extra functions to completions at point. This functions are listed in the custom variable =elisp-eldoc-flags-completions-functions= with default value:

- ~elisp-eldoc-flags-interactive-completion-at-point~ which completes inside string in the ~interactive~ form.

*** elisp-eldoc-flags-remove-completion-functions
Remove =elisp-eldoc-flags-completions-functions= from completions at point.
